apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: di
resources:
- sa.yaml
- deployment.yaml
images:
- name: jasonblanchard/di-entry
  newTag: 9e7b5ca4bd3f7e6a1494715beea81966e33e0e42
configMapGenerator:
- literals:
  - NATS_HOST=nats://nats:4222
  - DB_USER=di
  - DB_PASSWORD=di
  - DB_HOST=di-entry-psql
  - DB_PORT=5432
  - DB_DATABASE=di_entry
  name: di-entry-config
