---
apiVersion: v1
kind: ConfigMap
metadata:
  name: di-entry-init-db
  namespace: di
  labels:
    app: di-entry-jobs
data:
  POSTGRES_USER: di
  POSTGRES_PASSWORD: di
  DB_USER: di
  DB_PASSWORD: di
  DB_HOST: di-entry-psql
---
apiVersion: batch/v1
kind: Job
metadata:
  name: di-entry-init-db
spec:
  template:
    metadata:
    spec:
      containers:
      - image: postgres:10.7
        name: di-entry-init-db
        command:
          - /bin/bash
          - -c
          - |
            export PGPASSWORD=$DB_PASSWORD
            createdb -h $DB_HOST -U di -e -O di -w di_entry
        envFrom:
          - configMapRef:
              name: di-entry-init-db
      restartPolicy: Never
