---
apiVersion: v1
kind: ConfigMap
metadata:
  name: di-entry-migrations
  namespace: di
  labels:
    app: di-entry-jobs
data:
  DB_USER: di
  DB_PASSWORD: di
  DB_HOST: di-entry-psql
---
apiVersion: batch/v1
kind: Job
metadata:
  name: di-entry-migrations
spec:
  template:
    metadata:
    spec:
      containers:
      - image: jasonblanchard/di-entry # TODO: Kustomize this to get the sha?
        name: di-entry-migrations
        command:
          - npm
          - run
          - db:migrate:up
        envFrom:
          - configMapRef:
              name: di-entry-migrations
      restartPolicy: Never
